apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-cont
        image: nginx:1.9.1
        ports:
        - containerPort: 80
        volumeMounts:
          - name: sales-creds-volume
            mountPath: /usr/src/app/secret
      volumes:
      - name: sales-creds-volume
        secret:
          secretName: sales-creds
